services:
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    depends_on:
      - database
    stdin_open: true
    tty: true
    command: ["--url=https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-01.csv.gz", "--user_name=root", "--password=root", "--db=ny_taxi", "--host=postgres", "--port=5432"]

  database:
    container_name: postgres
    image: postgres:15.1
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    ports:
      - 5432:5432
    volumes:
      - ../play_around/ny_taxi_data:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8080:80
  
